name: Remove App_Offline - Emergency Fix
on:
  workflow_dispatch: # deploy manual

jobs:
  remove-app-offline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create empty directory
      run: mkdir -p temp_deploy
    
    - name: Create dummy file to delete app_offline.htm
      run: |
        cd temp_deploy
        echo "dummy" > dummy.txt
    
    - name: Remove App_Offline file via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: win8184.site4now.net
        username: itetech-001
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: './temp_deploy/'
        server-dir: /salasweb/
        dangerous-clean-slate: true
        include: |
          dummy.txt
        # Isso vai forçar a limpeza do app_offline.htm do servidor
