name: AutomacaoSalas-WEB CI

on:
  push:
    branches: [ feature/deploy-automatico ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      work-directory: Codigo/ModuloDeSoftware/WebAPI

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
      
    - name: Restore dependencies
      run: |
        cd ${{env.work-directory}}
        dotnet restore

    - name: Build Application
      run: |
        cd ${{env.work-directory}}
        dotnet build --no-restore
      
    - name: Publish Application
      run: |
        cd ${{env.work-directory}}
        dotnet publish -c --configuration Release --no-restore --output ./publish 
      
#    - name: Upload via FTP
#      uses: SamKirkland/FTP-Deploy-Action@4.3.0
#      with:
#        server: ${{ secrets.FTP_SERVER }}
#        username: ${{ secrets.FTP_USER }}
#        password: ${{ secrets.FTP_PASS }}
#        local-dir: publish/
#        remote-dir: ./
#        exclude: |
#          **/.git*
#          **/.git*/**