name: AutomacaoSalas-WEB Deploy (WebDeploy)
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    env:
      work-directory: Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
    
    - name: Replace connection string
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.work-directory}}/appsettings.json'
      env:
        ConnectionStrings.MySqlConnection: ${{secrets.CONNECTION_STRING}}
    
    - name: Restore dependencies
      run: |
        cd ${{env.work-directory}}
        dotnet restore
    
    - name: Build Application
      run: |
        cd ${{env.work-directory}}
        dotnet build --configuration Release --no-restore
    
    - name: Publish Application
      run: |
        cd ${{env.work-directory}}
        dotnet publish --configuration Release --no-build --output ./publishWEB
    
    # Deploy via dotnet publish direto (mais estável que FTP)
    - name: Deploy via WebDeploy
      run: |
        cd ${{env.work-directory}}
        dotnet publish --configuration Release --output ./publishWEB --verbosity normal /p:WebPublishMethod=FTP /p:PublishUrl=ftp://win8184.site4now.net/salasweb /p:UserName=itetech-001 /p:Password="${{ secrets.FTP_PASSWORD }}" /p:DeployOnBuild=true
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
